CREATE TABLE contacts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tel_number VARCHAR(15) NOT NULL,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    email VARCHAR(255),
    profession VARCHAR(255)
);

INSERT INTO contacts (tel_number, name, address, email, profession) VALUES
('555-1234', 'John Doe', '123 Main St, Cityville', 'john.doe@email.com', 'Engineer'),
('555-5678', 'Jane Smith', '456 Oak St, Townburg', 'jane.smith@email.com', 'Teacher'),
('555-9012', 'Bob Johnson', '789 Pine St, Villagetown', 'bob.johnson@email.com', 'Doctor'),
('555-3456', 'Alice Williams', '101 Cedar St, Hamletville', 'alice.williams@email.com', 'Artist'),
('555-7890', 'Charlie Davis', '202 Elm St, Suburbia', 'charlie.davis@email.com', 'Lawyer'),
('555-2345', 'Eva Miller', '303 Birch St, Countryside', 'eva.miller@email.com', 'Chef'),
('555-6789', 'David Wilson', '404 Maple St, Citytown', 'david.wilson@email.com', 'Journalist'),
('555-0123', 'Grace Martin', '505 Spruce St, Townville', 'grace.martin@email.com', 'Architect'),
('555-4567', 'Frank Taylor', '606 Ash St, Villageland', 'frank.taylor@email.com', 'Pilot'),
('555-8901', 'Helen Brown', '707 Pine St, Hamletburg', 'helen.brown@email.com', 'Scientist'),
('555-1235', 'George White', '808 Oak St, Suburbville', 'george.white@email.com', 'Entrepreneur'),
('555-5679', 'Linda Hall', '909 Cedar St, Countrysidetown', 'linda.hall@email.com', 'Nurse'),
('555-9013', 'Samuel Clark', '111 Elm St, Cityburg', 'samuel.clark@email.com', 'Developer'),
('555-3457', 'Sophia Harris', '222 Birch St, Townland', 'sophia.harris@email.com', 'Marketing Specialist'),
('555-7891', 'Michael Martinez', '333 Maple St, Villageside', 'michael.martinez@email.com', 'Police Officer'),
('555-2346', 'Olivia Anderson', '444 Spruce St, Hamletland', 'olivia.anderson@email.com', 'Pharmacist'),
('555-6790', 'Daniel Lee', '555 Ash St, Suburbtown', 'daniel.lee@email.com', 'Graphic Designer'),
('555-0124', 'Emma Wright', '666 Pine St, Cityside', 'emma.wright@email.com', 'Financial Analyst'),
('555-4568', 'William Turner', '777 Oak St, Villageburg', 'william.turner@email.com', 'Electrician'),
('555-8902', 'Isabella Harris', '888 Cedar St, Countrysideside', 'isabella.harris@email.com', 'Fitness Trainer'),
('555-1236', 'John Carter', '999 Elm St, Townside', 'john.carter@email.com', 'Event Planner'),
('555-5680', 'Mia Garcia', '121 Birch St, Cityland', 'mia.garcia@email.com', 'Dentist'),
('555-9014', 'Christopher Robinson', '232 Maple St, Villagesideville', 'christopher.robinson@email.com', 'Real Estate Agent'),
('555-3458', 'Ava Lewis', '343 Spruce St, Hamletside', 'ava.lewis@email.com', 'Writer'),
('555-7892', 'Ethan Hall', '454 Ash St, Suburbside', 'ethan.hall@email.com', 'Software Engineer'),
('555-2347', 'Grace Turner', '565 Pine St, Cityvilleburg', 'grace.turner@email.com', 'Mechanic'),
('555-6791', 'Liam Brown', '676 Oak St, Villageburgtown', 'liam.brown@email.com', 'Teacher'),
('555-0125', 'Chloe Martin', '787 Cedar St, Countrysidesidetown', 'chloe.martin@email.com', 'Chef'),
('555-4569', 'Jackson Wilson', '898 Elm St, Townvilleland', 'jackson.wilson@email.com', 'Lawyer'),
('555-8903', 'Sophie Anderson', '909 Birch St, Cityburgside', 'sophie.anderson@email.com', 'Architect'),
('555-1237', 'Daniel Harris', '121 Maple St, Villagesidevilletown', 'daniel.harris@email.com', 'Pilot'),
('555-5681', 'Aria Martinez', '232 Spruce St, Hamletsideville', 'aria.martinez@email.com', 'Scientist'),
('555-9015', 'James Turner', '343 Ash St, Suburbsideside', 'james.turner@email.com', 'Entrepreneur'),
('555-3459', 'Olivia Brown', '454 Pine St, Cityvilleland', 'olivia.brown@email.com', 'Nurse'),
('555-7893', 'Alexander White', '565 Oak St, Villageburgville', 'alexander.white@email.com', 'Developer'),
('555-2348', 'Ava Taylor', '676 Cedar St, Countrysidesideside', 'ava.taylor@email.com', 'Marketing Specialist'),
('555-6792', 'William Smith', '787 Elm St, Townburgside', 'william.smith@email.com', 'Police Officer'),
('555-0126', 'Emily Clark', '898 Birch St, Citysidevilletown', 'emily.clark@email.com', 'Pharmacist'),
('555-4570', 'Logan Johnson', '909 Maple St, Villagesidetown', 'logan.johnson@email.com', 'Graphic Designer'),
('555-8904', 'Sophia Davis', '121 Spruce St, Hamletvilleburg', 'sophia.davis@email.com', 'Financial Analyst'),
('555-1238', 'Mason Robinson', '232 Ash St, Suburbsidesidetown', 'mason.robinson@email.com', 'Electrician'),
('555-5682', 'Amelia Anderson', '343 Pine St, Citysideburg', 'amelia.anderson@email.com', 'Fitness Trainer'),
('555-9016', 'Elijah Turner', '454 Oak St, Villageburgvilletown', 'elijah.turner@email.com', 'Event Planner'),
('555-3460', 'Ella Martin', '565 Cedar St, Countrysidesideville', 'ella.martin@email.com', 'Dentist'),
('555-7894', 'Carter Harris', '676 Elm St, Townsideburg', 'carter.harris@email.com', 'Real Estate Agent'),
('555-2349', 'Avery Lewis', '787 Birch St, Cityvilleburgtown', 'avery.lewis@email.com', 'Writer'),
('555-6793', 'Liam Wilson', '898 Maple St, Villagesideside', 'liam.wilson@email.com', 'Software Engineer');
